### ISSUE TITLE
Error when querying suggestions

### ISSUE THREAD

**Issue by IIIuminator** [BjoernPetersen/MusicBot-desktop#44]
```ERROR net.bjoernpetersen.deskbot.rest.RestServer - An unknown error occurred.
java.lang.IllegalStateException: ctx.pathParam("max") must not be null
        at net.bjoernpetersen.deskbot.rest.handler.SuggesterHandler$suggestSongs$1.invoke(SuggesterHandler.kt:39)
        at net.bjoernpetersen.deskbot.rest.handler.SuggesterHandler$suggestSongs$1.invoke(SuggesterHandler.kt:19)
        at net.bjoernpetersen.deskbot.rest.FullAsyncBuilder$start$1.handle(AsyncHelper.kt:62)
        at net.bjoernpetersen.deskbot.rest.FullAsyncBuilder$start$1.handle(AsyncHelper.kt:53)
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:272)
        at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
```
when querying `/suggester/com.github.felixgail.musicbot.gplaymusic.GPlayMusicSuggesterBase?max=32`

Results in an internal server error

**Comment by BjoernPetersen** [comment]
Thanks, fixed with 13899804d00456372a51de91935fe6a4dbf7dd01
