### ISSUE TITLE
Password can't be changed after being set

### ISSUE THREAD

**Issue by IIIuminator** [BjoernPetersen/MusicBot-desktop#59]
When call the `changePassword` endpoint after the user has been upgraded to a full user the following error occurs:
```
net.bjoernpetersen.musicbot.api.auth.DuplicateUserException: org.sqlite.SQLiteException: [SQLITE_CONSTRAINT]  Abort due to constraint violation (UNIQUE constraint failed: users.id)
        at net.bjoernpetersen.musicbot.internal.auth.DefaultDatabase.insertUser(DefaultDatabase.kt:99)
        at net.bjoernpetersen.musicbot.api.auth.UserManager.updateUser(UserManager.kt:85)
        at net.bjoernpetersen.deskbot.rest.handler.UserHandler$changePassword$1.invoke(UserHandler.kt:47)
        at net.bjoernpetersen.deskbot.rest.handler.UserHandler$changePassword$1.invoke(UserHandler.kt:18)
        at net.bjoernpetersen.deskbot.rest.FullAsyncBuilder$start$1.handle(AsyncHelper.kt:62)
...internal vertx, sqlite and java stuff...
```

**Comment by BjoernPetersen** [comment]
The bug here was that the `DuplicateUserException` isn't caught and converted to a 409 response.

The fact that the bot detects a conflict is simply because you're trying to set a password using a `Guest` token. If you use the token you receive as a response for the first `changePassword` call, you can change your password just fine.
