### ISSUE TITLE
NoSuchElementException when default suggester has no suggestions on startup

### ISSUE THREAD

**Issue by FelixGail** [BjoernPetersen/MusicBot-desktop#70]
```java
[DefaultDispatcher-worker-3] WARN net.bjoernpetersen.musicbot.internal.player.ActorPlayer - May be cancellation in ActorPlayer actor loop
java.util.NoSuchElementException
	at java.util.LinkedList.removeFirst(LinkedList.java:270)
	at java.util.LinkedList.pop(LinkedList.java:801)
	at net.bjoernpetersen.localmp3.suggester.RandomMp3Suggester.suggestNext(RandomMp3Suggester.kt:69)
	at net.bjoernpetersen.musicbot.internal.player.SyncPlayer.next(ActorPlayer.kt:191)
	at net.bjoernpetersen.musicbot.internal.player.SyncPlayer$next$1.invokeSuspend(ActorPlayer.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:561)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:727)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:667)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:655)
```

**Comment by BjoernPetersen** [comment]
This seems to actually be a bug in the RandomMp3Suggester plugin. It shouldn't throw a `NoSuchElementException`, but a `BrokenSuggesterException`

**Comment by BjoernPetersen** [comment]
This has been fixed on the `develop` branch of the [MusicBot-plugins](../../MusicBot-plugins) repo.
